name: Build and Push Docker Image

# On Duty --- Like checking if something will change in master branch, then Job should execute 
on:
  push:
    branches:
      - master #Trigger from master branch
    paths:
      - '**/*' #Any changes in master branch

#If changes done, then below job will execute and there are steps mentioned 

jobs:
  Build:  # Build for like env, where docker build command will run, like docker runner
    runs-on: ubuntu-latest

    steps: 
      - name: checkout code
        uses: actions/checkout@v2 #1 step - it pulls down the latest code from your GitHub repository to the runner mechine(above mentioned ubuntu)

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2 # 2 Step - ensures that the runner has Docker Buildx installed and ready to use for building your Docker images with advanced features.
      - name: Check Secrets (Debug)
        run: |
          echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}"

      - name: Login in to Docker Hub 
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Image
        run: |
          docker build -t 1nfosecsingh/weather-check-app:latest .

      - name: Push Image
        run: |
          docker push 1nfosecsingh/weather-check-app:latest
